In [1]:
#Importin libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [3]:
#Importing project data frame:

#Loading raw DataFrame 
path = r'C:\Users\isaac\Documents\CareerFoundry\2. Data Inmersion\6. Advanced Analytics & Dashboard Design\Data Bases\World Bank-WDI_CSV_2024_09_25'
df2 = pd.read_csv(os.path.join(path, 'WDICountry.csv'))

In [5]:
df2.head()

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,...,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,NaN
1,AFE,Africa Eastern and Southern,Africa Eastern and Southern,Africa Eastern and Southern,ZH,NaN,"26 countries, stretching from the Red Sea in t...",NaN,NaN,ZH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,The reporting period for national accounts dat...,South Asia,Low income,AF,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,NaN
3,AFW,Africa Western and Central,Africa Western and Central,Africa Western and Central,ZI,NaN,"22 countries, stretching from the westernmost ...",NaN,NaN,ZI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,The World Bank systematically assesses the app...,Sub-Saharan Africa,Lower middle income,AO,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2018.0,NaN

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 31 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country Code                                       265 non-null    object
 1   Short Name                                         265 non-null    object
 2   Table Name                                         265 non-null    object
 3   Long Name                                          265 non-null    object
 4   2-alpha code                                       263 non-null    object
 5   Currency Unit                                      217 non-null    object
 6   Special Notes                                      127 non-null    object
 7   Region                                             217 non-null    object
 8   Income Group                                       216 non-null    object
 9   WB-2 code                                          264 non-null    object
 10  National accounts base year                        214 non-null    object
 11  National accounts reference year                   80 non-null     float64
 12  SNA price valuation                                208 non-null    object
 13  Lending category                                   145 non-null    object
 14  Other groups                                       60 non-null     object
 15  System of National Accounts                        214 non-null    object
 16  Alternative conversion factor                      0 non-null      float64
 17  PPP survey year                                    0 non-null      float64
 18  Balance of Payments Manual in use                  195 non-null    object
 19  External debt Reporting status                     122 non-null    object
 20  System of trade                                    172 non-null    object
 21  Government Accounting concept                      158 non-null    object
 22  IMF data dissemination standard                    188 non-null    object
 23  Latest population census                           214 non-null    object
 24  Latest household survey                            154 non-null    object
 25  Source of most recent Income and expenditure data  168 non-null    object
 26  Vital registration complete                        120 non-null    object
 27  Latest agricultural census                         128 non-null    object
 28  Latest industrial data                             147 non-null    float64
 29  Latest trade data                                  191 non-null    float64
 30  Latest water withdrawal data                       0 non-null      float64
dtypes: float64(6), object(25)
memory usage: 64.3+ KB

### Many variables will be drop for better data usability.

In [18]:
# List of columns to drop
columns_to_drop = [
    'Table Name',
    'Long Name',
    '2-alpha code',
    'Special Notes',
    'WB-2 code',
    'National accounts base year',
    'National accounts reference year',
    'SNA price valuation',
    'System of National Accounts',
    'Alternative conversion factor',
    'PPP survey year',
    'Balance of Payments Manual in use',
    'External debt Reporting status',
    'System of trade',
    'Government Accounting concept',
    'IMF data dissemination standard',
    'Latest population census',
    'Latest household survey',
    'Source of most recent Income and expenditure data',
    'Vital registration complete',
    'Latest agricultural census',
    'Latest industrial data',
    'Latest trade data',
    'Latest water withdrawal data'
]

# Drop the specified columns
df2_cleaned = df2.drop(columns=columns_to_drop)

# Check the structure of the cleaned DataFrame
print(df2_cleaned.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country Code      265 non-null    object
 1   Short Name        265 non-null    object
 2   Currency Unit     217 non-null    object
 3   Region            217 non-null    object
 4   Income Group      216 non-null    object
 5   Lending category  145 non-null    object
 6   Other groups      60 non-null     object
dtypes: object(7)
memory usage: 14.6+ KB
None

### Exporting DataFrame to CSV:

In [23]:
# Specify the file path
output_path = r'C:\Users\isaac\Documents\CareerFoundry\2. Data Inmersion\6. Advanced Analytics & Dashboard Design\Data Bases\WDI2.csv'

# Export the cleaned DataFrame to CSV
df2_cleaned.to_csv(output_path, index=False)

print(f'DataFrame exported successfully to: {output_path}')

DataFrame exported successfully to: C:\Users\isaac\Documents\CareerFoundry\2. Data Inmersion\6. Advanced Analytics & Dashboard Design\Data Bases\WDI2.csv